version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api:
    build:
      context: src
      dockerfile: build/api/Dockerfile
    depends_on:
      - kafka
      - clickhouse
    environment:
      - KAFKA_BROKER=kafka:9092
      - CLICKHOUSE_HOST=clickhouse
    ports:
      - 0.0.0.0:${HOST_HTTP_PORT}:8080
      - 0.0.0.0:${METRIC_HTTP_PORT}:8083

volumes:
  clickhouse_data: